### ISSUE TITLE
[Proposal]configuration proposal

### ISSUE THREAD

**Issue by wentevill** [wentevill/cs-automate#1]
## Motivation

A mechanism is needed to configure the key or configuration file only once in the cluster, and other namespaces can be automatically injected within the allowed range.
## Goal

Users add secret or configuration files in the cluster, and create secret or configuration files synchronously in the allowed namespace.

## Proposal

The following CRDs can be defined to record the keys or configuration files that need to be automatically injected into the namespace.
```yaml
apiVersion: automate.io/v1alpha1
kind: Configuration
metadata:
  name: sample
spec:
  scopes:
    - default
    - kube-system
    - kube-public
  references:
    - kind: ConfigMap
      apiVersion: 
      names:
        - sample-config
```
